export const gear = {
    zcbmasori: {
        acc:251,
        str:149,
        aspd:5,
        setbonus:[1,1],
        dragonbane:false,
        ruby:true,
        info: 'ZCB + Masori',
    },
    zcbdhides: {
        acc:217,
        str:139,
        aspd:5,
        setbonus:[1,1],
        dragonbane:false,
        ruby:true,
        info: 'ZCB + Dhides',
    },
    bofa: {
        acc:221,
        str:113,
        aspd:4,
        setbonus:[1.15,1.3],
        dragonbane:false,
        ruby:false,
        info: 'Bofa + Crystal',
    },
    bpmasori: {
        acc:147,
        str:70,
        aspd:2,
        setbonus:[1,1],
        dragonbane:false,
        ruby:false,
        info: 'BP + DDartsa + Masori',
    },
    dcbmasori: {
        acc:229,
        str:147,
        aspd:5,
        setbonus:[1,1],
        dragonbonus:[1,1],
        dragonbane:false,
        ruby:true,
        info: 'DHCB + Dhides',
    },
    dhcbdhides: {
        acc:195,
        str:139,
        aspd:5,
        setbonus:[1.25, 1.3],
        dragonbonus:[1.25, 1.3],
        dragonbane:true,
        ruby:true,
        info: 'DHCB + Dhides',
    },
    dhcbmasori: {
        acc:236,
        str:149,
        aspd:5,
        setbonus:[1.25, 1.3],
        dragonbonus:[1.25, 1.3],
        dragonbane:true,
        ruby:true,
        info: 'DHCB + Masori',
    }
};